version: "3.8"

services:
  docs-solando:
    image: nginx:alpine-slim
    restart: unless-stopped
    volumes:
      - ./project:/usr/share/nginx/html
      - ./default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - kingston-net

networks:
  kingston-net:
    external: true
